### PR TITLE
Team Oops Changes

### PR DESCRIPTION
**Pull request by rarar0**
Changed all instances of "TeamOps" to "TeamOops", updated teamOops.html with brief description and links (and a picture)

### CODE REVIEW

**Comment by rarar0** [comment]
I don't see any review comments, you can ask me questions in the comment field here.

**Review by RonyValle — COMMENTED** [review]
We have review your changes. I think there is no need to rename the teamOps.html to teamOops.html
because this will mean that the html file store in the server will need to be rename as well. 
I think the following should be just fine:
`<li><a href="teamOps.html">TeamOops</a></li>`

Every instance of the name teamOps on the webpage will be displayed as TeamOops Which is what im guessing you want.

**Comment by rarar0** [comment]
If you do a git pull on the server wouldn't it update all files automatically with my edits? I'm fine with not changing the filename as long as it appears as TeamOops on the website, that was the change I had in mind.

**Comment by RonyValle** [comment]
It would not update the name of the actual teamOps.html file. so there would be a broken link to your teams web page.  using the line of code i provided above will have the desired changes ;)

**Comment by rarar0** [comment]
I went ahead and made those changes! Should keep the link and display as oops on the site!

**Comment by RonyValle** [comment]
Sorry for the extra work! Everything seems good I will Merge the pull request now. Someone else will make the changes on the server so that your edits show on the live website.

**Pull request merged**
